### ISSUE TITLE
[Main Box] ToDo List 퍼블리싱

### ISSUE THREAD

**Issue by wonyj0228** [wonyj0228/TodoTodo#12]
TODO

- [x] Status Box
- [x] Delete All Button
- [x] Delete Button
- [x] Delete Button 활성화 시 디자인

- [x] ToDo 컴포넌트
- [x] ToDo 컴포넌트 완료시 디자인
- [x] ToDo 컴포넌트 삭제 활성화 시 디자인
