### ISSUE TITLE
[Main Box] ToDo Item 추가 기능 구현

### ISSUE THREAD

**Issue by wonyj0228** [wonyj0228/TodoTodo#13]
TODO

- [x] TODO 입력시 추가 이벤트 구현
- [x] 랜덤 색깔 구현
- [x] Status 업데이트 구현
- [x] Toggle 클릭 이벤트 구현
   - [x] Off시 text 줄긋기, 컴포넌트 색상 어둡게 변경
